import { Inter } from "next/font/google";
import "./globals.css";
import Button from "./Button";
import {Heroimg,Imagem1,Imagem2,Imagem3,Img} from "../../public/img/imagem";
import { Card } from "../../public/img/logo";
import Serviços, {Article} from "./Services";
import App, { Questions } from "./FAQsection";
import Footer from "./Footer";
//d
import Logo from "./Logo";
import NavBar from "./Navbar";
import TextoSection,{ Botao,Hero} from "./Main";
import Hero2,{ImagemSection} from "./Site";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
  <html lang="en">
  <head></head>
  <body className="bg-red-700"> 
  <header className="w-full absolute top-0 left-0 flex justify-between items-center px-10 py-1 bg-red-600 animate-fade-in">
        <a href="#"><img src="/img/BDQ MICROCREDITO LOGO 1.png" alt="" className="w-20" /></a> 
        <nav className="flex">
          <ul className="flex space-x-20">
            <li className="mr-8">
              <a href="#" className="text-white transition duration-300 ease-in-out hover:text-yellow-300">Home</a>
            </li>
            <li className="mr-8">
              <a href="#" className="text-white transition duration-300 ease-in-out hover:text-yellow-300">Sobre</a>
            </li>
            <li className="mr-8">
              <a href="#" className="text-white transition duration-300 ease-in-out hover:text-yellow-300">Serviços</a>
            </li>
            <li>
              <a href="#" className="text-white transition duration-300 ease-in-out hover:text-yellow-300">Suporte</a>
            </li>
          </ul>
        </nav>
      </header>
      
      <div className="relative mt-80 ml-10 mb-6">
        <h1 className="text-white text-4xl">Transforme seus sonhos <br /> em realidade com nosso <br /> microcrédito</h1>
        <button className="border-2 border-white text-white py-2 px-6 rounded-lg ml-15 mt-10">ver mais</button>
        <div className="absolute right-0 bottom-0 mb-10">
          <img src="/img/BDQ MICROCREDITO LOGO 1.png" alt="Descrição da imagem" className="w-40" style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }} />
        </div>
      </div>

      
              {/* Section 1 */}
      <section className="bg-white">
      <div className="flex justify-center justify-around">
        <Hero2 />
        <ImagemSection />
      </div>
    </section>
                {/* Section 2 */}
          <section>
          <h2 className="pt-7 m-5 text-2xl md:text-3xl lg:text-3xl font-bold mb-4 text-center">Lorem ipsum</h2>
                <p className="pt-9 m-5 text-1xl md:text-1xl lg:text-1xl mb-4 text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          <div className="pt-9 flex justify-center gap-5">
            {/* CARD'S */}
             <Card 
              image="./img/snail-icon.png"
              title="Missão"
            />
             <Card 
              image="./img/Old-Technology.png"
              title="Missão"
            />
             <Card 
              image="./img/price-icon.png"
              title="Missão"
            />
          </div>           
            </section>
            {/* SECTION 2 */}
              <div className="pt-9">
                <Serviços
              /></div>
              {/*  LAST SECTION */}

              <section className="pt-10">
                <Article/>
              </section>
              <section className="bg-white text-black pt-12">
              <App />
              <Questions/>
              </section>
              <footer className="">
                <Footer/>
              </footer>
  </body>
  </html>
  );
}
